export const DATA: any = {
  london: {
    roadmap: [
      { phase: "J-30", title: "Préparation Paris-Londres", items: ["Confirmer Eurostar Paris–Londres 28 mai", "Briefing Thomas Lambert (Lazard) — pipeline Lagos + ATS", "RDV HEC Africa Club Paris — diaspora franco-nigériane", "Réserver salle dîner privé Londres (8 profils diaspora NG/GH)"] },
      { phase: "J-1", title: "Arrivée Londres — RDV bilatéraux", items: ["Eurostar arrivée 11h St Pancras", "3 RDV fonds UK-Africa pré-planifiés (après-midi)", "Dîner privé : 8 profils diaspora nigériane/ghanéenne"] },
      { phase: "J0", title: "Africa Tech Summit — London Stock Exchange", items: ["08h30 Accueil LSE — networking pre-sessions", "09h30 Keynotes — cartographie présences", "11h00 Sessions fonds : Helios, AfricInvest", "13h00 Déjeuner networking : 5 cibles, table réservée", "15h00 RDV Tomi Davies (TVC Labs)", "18h00 Cocktail clôture — scoring contacts"] },
      { phase: "J+1", title: "Consolidation Londres", items: ["4 RDV de suivi 1-on-1 post-ATS", "Déjeuner Africa desk BNP Paribas/SocGen", "16h00 Eurostar retour Paris", "Dîner bilatéral contacts Jeune Afrique"] },
      { phase: "J+2", title: "Paris — Suivi bilatéraux", items: ["Sciences Po Alumni Africa — déjeuner 10 profils", "HEC Africa Business Club — officialisation partenariat", "Bilan semaine : scoring 40 contacts P0-P3"] },
    ],
    people: [
      { name: "Tomi Davies", org: "TVC Labs", role: "Connecteur central écosystème tech nigérian", priority: "P0", action: "RDV 30 min confirmé via ATS B2B platform" },
      { name: "Babatunde Sovoye", org: "Helios Investment Partners", role: "LP potentiel CG — fonds infrastructure Afrique", priority: "P0", action: "Approche via Investor Forum ATS" },
      { name: "Direction AfricInvest", org: "AfricInvest", role: "Fonds PE franco-africain, co-investissement corridor", priority: "P1", action: "Email pré-ATS via Thomas Lambert" },
      { name: "Africa desk leads", org: "BNP Paribas / SocGen London", role: "Financement infrastructure corridor", priority: "P1", action: "Déjeuner J+1 post-ATS" },
      { name: "Laurdi Sala-Diakanda", org: "Jeune Afrique", role: "Réseau médias panafricain premium", priority: "P1", action: "Dîner bilatéral soir J+1" },
      { name: "Diaspora NG/GH London (5 profils)", org: "Divers C-level", role: "Introducteurs vers Lagos + chapitre Londres M12+", priority: "P0", action: "Dîner privé soir J-1" },
    ],
    companies: [
      { name: "Helios Investment Partners", type: "Fonds PE", relevance: "LP potentiel CG — plus grand fonds infrastructure Afrique basé à Londres" },
      { name: "AfricInvest", type: "Fonds PE", relevance: "Franco-africain, tickets Series A/B corridor — co-deals CG" },
      { name: "London Stock Exchange Group", type: "Bourse", relevance: "Cotation AIM futures entreprises CG cohorte 2+" },
      { name: "Founders Factory Africa", type: "Accélérateur", relevance: "UK-Africa, profils cohorte CG, deal flow partagé" },
      { name: "Techstars Africa alumni", type: "Réseau", relevance: "Fondateurs Série A+ diaspora londonienne" },
      { name: "Bank of America London", type: "Banque", relevance: "Africa desk — financement infrastructure" },
    ],
    campus: [
      { name: "LSE Africa Society", profile: "Étudiants africains grandes institutions", action: "Contacter président société — proposer event CG post-ATS" },
      { name: "Imperial College Africa Alumni", profile: "Profils deeptech, énergie, infrastructure", action: "Via réseau alumni — cibler PhDs africains en énergie" },
      { name: "Oxford Africa Society", profile: "Hauts fonctionnaires et diplomates en formation", action: "Proposer intervention CG lors d'un Oxford Africa event S2 2026" },
      { name: "SOAS University", profile: "Études africaines, économie du développement", action: "Réseau académique pour légitimité think tank CG" },
    ],
    networks: [
      { name: "Moroccan British Business Council", type: "Institutionnel", action: "Email direction — partenariat CFC London" },
      { name: "Chambre de Commerce franco-britannique", type: "Réseau entreprises", action: "Demander liste membres actifs Afrique" },
      { name: "Total / BNP Paribas London Africa desks", type: "Corporate", action: "Via Thomas Lambert pour introductions" },
      { name: "Alumni Sciences Po / ENA London", type: "Alumni", action: "Hauts fonctionnaires franco-africains basés UK" },
    ],
    communities: [
      { name: "OCP Europe desk Londres", role: "Réseau OCP anglophone — diaspora corporate marocaine" },
      { name: "Attijariwafa London branch", role: "Banque marocaine de référence à Londres — réseau naturel" },
      { name: "TVC Labs Nigeria London", role: "Réseau fondateurs tech Lagos basés Londres" },
    ],
    objectives: [
      { title: "3 fonds anglophones briefés sur CG", kpi: "3 term sheets d'intérêt LP", status: "pending" },
      { title: "5 profils nigérians/ghanéens diaspora London", kpi: "5 contacts diaspora NG/GH", status: "pending" },
      { title: "RDV Tomi Davies / TVC Labs confirmé", kpi: "1 RDV TVC Labs", status: "pending" },
      { title: "Chapitre Londres CG initié", kpi: "3 membres fondateurs identifiés", status: "pending" },
    ],
    opportunities: [
      { axis: "Capital", title: "LSE AIM comme venue cotation futures entreprises CG", desc: "Cotation possible cohorte 2 avec traction suffisante — ATS prépare ce terrain 3 ans à l'avance" },
      { axis: "Diaspora", title: "Chapitre Londres CG M12+", desc: "Concentration diaspora africaine qualifiée justifie un chapitre — ATS est le recrutement fondateur" },
      { axis: "Anglophones", title: "Pont Ghana-Nigeria via diaspora UK", desc: "Profils biculturels franco-anglophone — relais naturels marchés anglophones corridor" },
    ],
    logistics: [
      { item: "Eurostar Paris–Londres", cost: "120–180€ A/R", timing: "Réserver J-21", notes: "Départ 08h Gare du Nord, arrivée 11h St Pancras" },
      { item: "Hôtel Londres (2 nuits)", cost: "300–500€", timing: "Réserver J-30", notes: "Proximité LSE — zone City/Bank" },
      { item: "Badge ATS London", cost: "450–800£", timing: "Inscription J-30", notes: "Investor tier si disponible" },
      { item: "Restaurant dîner privé (8 pers.)", cost: "400–600£", timing: "Réserver J-21", notes: "Private dining room, City ou Mayfair" },
      { item: "Mémorandums CG imprimés", cost: "Inclus kit GITEX", timing: "Prêts J-7", notes: "20 exemplaires pour Londres" },
    ],
    followup: [
      { timing: "J+0", action: "Scoring immédiat des contacts ATS", tool: "Grille Excel", kpi: "20 contacts scorés" },
      { timing: "J+1", action: "Emails personnalisés aux 5 contacts P0", tool: "Email + mémorandum PDF", kpi: "5 emails" },
      { timing: "J+3", action: "Connexions LinkedIn avec notes", tool: "LinkedIn", kpi: "20 connexions" },
      { timing: "J+7", action: "Relance Tomi Davies — confirmation pipeline Lagos", tool: "Email/WhatsApp", kpi: "1 RDV confirmé" },
      { timing: "J+14", action: "Propositions formelles aux 3 fonds briefés", tool: "Email + deck investisseur", kpi: "3 propositions" },
      { timing: "J+30", action: "Rapport ATS London — bilan et projection chapitre", tool: "Document interne", kpi: "1 rapport" },
    ],
    programme12: {
      cityRole: "Sourcing Demo Day + Diaspora Cohorte",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Sourcing candidats", status: "secondary", partners: [
          { name: "LSE Africa Society", type: "Campus", action: "Identifier 3-5 candidats anglophones pour cohorte — profils finance/policy", deliverable: "5 candidatures qualifiées" },
          { name: "Imperial College Africa Alumni", type: "Campus", action: "PhDs africains en énergie/deeptech — profils co-fondateurs techniques", deliverable: "3 profils techniques scorés" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Non applicable", status: "na", partners: [
          { name: "—", type: "—", action: "Londres n'est pas une ville Phase II. Les équipes valident à Lagos, Dakar ou Casablanca.", deliverable: "—" },
        ]},
        { phase: "Phase III — Demo Day", role: "Audience investisseurs anglophone", status: "primary", partners: [
          { name: "Helios Investment Partners", type: "LP/Fonds", action: "Confirmer présence au Demo Day — premier investisseur anglophone dans la salle", deliverable: "1 confirmation Demo Day" },
          { name: "AfricInvest", type: "Fonds PE", action: "Invitation formelle Demo Day — co-investissement post-programme", deliverable: "1 confirmation Demo Day" },
          { name: "Founders Factory Africa", type: "Accélérateur", action: "Partenariat deal flow post-Demo Day — startups CG dans leur pipeline", deliverable: "1 accord deal flow" },
          { name: "Diaspora NG/GH family offices", type: "Angels", action: "Constituer un syndicate de 5-8 diaspora angels pour le Demo Day", deliverable: "5 angels pré-engagés" },
        ]},
      ],
    },
  },
  paris: {
    roadmap: [
      { phase: "J-30", title: "Préparation VivaTech", items: ["Inscription VivaTech — badge Investor/Business", "Réserver restaurant dîner privé CG (25 pers., J2 ou J3 soir)", "Email intro Thomas Lambert → Elaia Partners", "Contacter Station F délégation Afrique — liste résidents africains"] },
      { phase: "J1", title: "VivaTech Ouverture + AfricaTech Village", items: ["09h00 Reconnaissance AfricaTech Village stands", "10h30 Keynotes — cartographie speakers africains", "14h00 AfricaTech Village : scoring 6 finalistes Award", "17h00 Tentative contact Tony Elumelu via entourage", "20h00 Dîner privé CG Marais — 15 fondateurs francophones"] },
      { phase: "J2", title: "Investisseurs & Fonds", items: ["09h00 Investor lounge — 6 RDVs fonds LP", "13h00 Déjeuner BPI France Direction Afrique", "15h00 AfricaTech Award pitch final — 2 équipes CG", "19h00 Dîner privé CG — 25 profils dont 10 anglophones"] },
      { phase: "J3", title: "Corporate & Annonce CG", items: ["09h30 CAC40 Africa desks : Total, Orange, LVMH", "12h00 Annonce officielle CG (option) — AfricaTech Village", "14h00 Station F residents africains — networking structuré", "16h00 Entourage Elumelu : RDV de suivi"] },
      { phase: "J4", title: "Clôture & Consolidation", items: ["09h00 Derniers RDVs — clôture VivaTech", "14h00 Scoring total 4 jours : 50+ contacts", "17h00 Plan de suivi 30 jours : 10 P0-P1 relancés"] },
    ],
    people: [
      { name: "Tony Elumelu", org: "Heirs Holdings / UBA", role: "Porte d'entrée élite business nigériane — P0 absolu", priority: "P0", action: "Approche via entourage ou intermédiaire VivaTech" },
      { name: "Direction BPI France Afrique", org: "BPI France", role: "Financement co-deals franco-africains", priority: "P1", action: "RDV stand officiel J2" },
      { name: "6 finalistes AfricaTech Award", org: "Startups africaines", role: "Profils cohorte 1 CG directement", priority: "P0", action: "Scoring compatibilité CG pendant pitchs J2" },
      { name: "Partech Africa team", org: "Partech", role: "Fonds VC franco-africain — LP potentiel et co-deals", priority: "P1", action: "RDV Investor Lounge VivaTech" },
      { name: "RAISE Africa desk", org: "RAISE", role: "Fonds impact — profils alignés corridor", priority: "P1", action: "Via réseau VivaTech Investor" },
      { name: "Résidents Station F africains", org: "Station F", role: "30+ fondateurs africains résidents Paris", priority: "P1", action: "Networking structuré 30 min J3" },
    ],
    companies: [
      { name: "BPI France International", type: "Institution financement", relevance: "Stand officiel — contact direct financement franco-africain" },
      { name: "Partech Africa", type: "Fonds VC", relevance: "Plus gros fonds VC dédié Afrique basé à Paris — LP et co-deals" },
      { name: "Station F", type: "Incubateur", relevance: "30+ résidents africains — vivier fondateurs cohorte CG" },
      { name: "Total / LVMH / Orange", type: "CAC40", relevance: "Africa desks directions innovation — clients futurs startups CG" },
      { name: "Elaia Partners", type: "Fonds VC deeptech", relevance: "Introduction via Thomas Lambert — thèse deeptech alignée" },
      { name: "France Digitale / Numeum", type: "Réseau tech", relevance: "Startups françaises co-investisseurs corridor" },
    ],
    campus: [
      { name: "HEC Paris — Africa Club", profile: "MBA + Grande École, fondateurs Africa en résidence", action: "Officialiser partenariat HEC Africa x CG — event conjoint S2" },
      { name: "ESSEC Startup Lab", profile: "Fondateurs en résidence, programmes entrepreneuriat", action: "Proposer case study CG comme exercice pédagogique" },
      { name: "Sciences Po — Africa Fellows", profile: "Think tank et policy — profils institutionnels", action: "Déjeuner Alumni Africa J+2 post-ATS (10 profils)" },
      { name: "Paris Dauphine Africa Hub", profile: "Finance, économie du développement", action: "Intervention CG lors d'un séminaire Africa Hub" },
      { name: "Centrale Supélec Alumni Africa", profile: "Ingénieurs franco-africains, diaspora technique", action: "Via réseau Centrale Casablanca pour cross-intro" },
    ],
    networks: [
      { name: "APEBI / CGEM Innovation stand", type: "Institutionnel marocain", action: "Présence marocaine officielle — réseau naturel CG" },
      { name: "Diaspora marocaine tech Paris", type: "Communauté", action: "Concentration maximale sur VivaTech — dîner J1" },
      { name: "MEDEF International Afrique", type: "Patronat", action: "Via Ambition Africa network — DG filiales" },
      { name: "Chambre de Commerce Franco-Africaine", type: "Réseau entreprises", action: "Membres actifs corridor — liste pré-VivaTech" },
    ],
    communities: [
      { name: "Startups marocaines finalistes VivaTech", role: "Alumni Outlierz, UM6P Ventures, Maroc Numeric" },
      { name: "BPI France Direction Afrique", role: "Stand officiel — contact direct financement" },
      { name: "France Digitale / Numeum", role: "Réseau startups françaises co-investisseurs" },
    ],
    objectives: [
      { title: "RDV Tony Elumelu planifié ou obtenu", kpi: "1 contact Elumelu/entourage", status: "pending" },
      { title: "6 finalistes AfricaTech Award scorés", kpi: "2 startups pipeline cohorte", status: "pending" },
      { title: "Dîner privé CG en marge — 25 profils", kpi: "25 participants", status: "pending" },
      { title: "Cohorte diaspora Paris complétée", kpi: "10 nouveaux contacts membres potentiels", status: "pending" },
      { title: "Annonce publique CG (option)", kpi: "1 prise de parole AfricaTech Village", status: "pending" },
    ],
    opportunities: [
      { axis: "Nigeria P0", title: "Tony Elumelu sans vol Lagos", desc: "Inaccessible à Lagos — à Paris la barrière s'effondre. Fenêtre la plus efficiente." },
      { axis: "Recrutement", title: "Cohorte diaspora Paris complète", desc: "4 jours pour compléter le recrutement diaspora Paris (cible 30 membres)" },
      { axis: "Communication", title: "Annonce publique CG lors VivaTech", desc: "Presse internationale présente — AfricaTech Village comme scène naturelle" },
    ],
    logistics: [
      { item: "Badge VivaTech (4 jours)", cost: "200–500€", timing: "J-30", notes: "Business/Investor tier" },
      { item: "Restaurant dîner privé (25 pers.)", cost: "2 000–4 000€", timing: "J-30", notes: "Private dining Paris 8e/Marais — 2 soirées" },
      { item: "Mémorandums CG", cost: "Inclus", timing: "J-7", notes: "30 exemplaires" },
      { item: "Déplacements Paris", cost: "100€", timing: "—", notes: "Métro/taxi Porte de Versailles" },
    ],
    followup: [
      { timing: "J+0", action: "WhatsApp aux 15 meilleurs contacts fondateurs", tool: "WhatsApp Business", kpi: "15 messages" },
      { timing: "J+1", action: "Emails personnalisés fonds + Tony Elumelu entourage", tool: "Email + PDF", kpi: "10 emails" },
      { timing: "J+3", action: "Scoring total : 50+ contacts classés P0-P3", tool: "Excel", kpi: "50 contacts" },
      { timing: "J+7", action: "Relance 5 contacts P0", tool: "Appel/Email", kpi: "5 relances" },
      { timing: "J+14", action: "Confirmation partenariat HEC Africa Club", tool: "Email direction", kpi: "1 partenariat" },
      { timing: "J+30", action: "Rapport VivaTech complet", tool: "Document interne", kpi: "1 rapport" },
    ],
    programme12: {
      cityRole: "Ville Phase I — Cristallisation & Formation d'Équipes",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Ville hôte principale", status: "primary", partners: [
          { name: "Station F — Délégation Afrique", type: "Incubateur", action: "Signer accord hébergement cohorte CG Phase I : 4 semaines, espace dédié, accès mentors Station F", deliverable: "1 accord Station F signé" },
          { name: "HEC Paris Africa Club", type: "Campus", action: "Partenariat recrutement : candidats HEC MBA + Grande École pour cohorte", deliverable: "1 partenariat HEC formalisé" },
          { name: "Sciences Po Africa Fellows", type: "Campus/Think tank", action: "Accès réseau policy + experts réglementaires pour workshops Phase I", deliverable: "3 experts policy confirmés" },
          { name: "Avocats multi-juridictions Paris", type: "Expert", action: "Identifier 2 cabinets OHADA + droit français prêts à intervenir en workshop structuration juridique", deliverable: "2 cabinets engagés" },
          { name: "Partech / Elaia / RAISE", type: "Fonds VC", action: "Recruter 5 partners VC comme mentors programme : product, growth, finance, pitch coaching", deliverable: "5 mentors VC confirmés" },
          { name: "BPI France Direction Afrique", type: "Institution", action: "Partenariat co-financement cohorte ou accès programmes BPI pour startups franco-africaines", deliverable: "1 accord BPI exploré" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Non applicable", status: "na", partners: [
          { name: "—", type: "—", action: "La Phase II se déroule à Lagos, Dakar et Casablanca — pas à Paris.", deliverable: "—" },
        ]},
        { phase: "Phase III — Création & Lancement", role: "Support juridique & pitch", status: "secondary", partners: [
          { name: "Cabinets OHADA Paris", type: "Juridique", action: "Structuration holding, filiales, pacte d'associés — support Phase III", deliverable: "Templates juridiques prêts" },
          { name: "Diaspora VivaTech (25 profils dîner)", type: "Réseau", action: "Reconvertir le dîner CG en « lancement programme 12 semaines » — narratif plus puissant", deliverable: "25 participants briefés sur programme" },
        ]},
      ],
    },
  },
  dakar: {
    roadmap: [
      { phase: "J-30", title: "Préparation axe Énergie", items: ["Cartographie 20 acteurs TSGP tronçon nord", "Email Attijariwafa Dakar — réseau Benjelloun-Touimi", "Contact ONHYM pour présence conjointe", "Réserver King Fahd Palace ou Terrou-Bi"] },
      { phase: "J-1", title: "Arrivée Dakar + Institutionnels", items: ["12h00 Arrivée Dakar", "15h00 Briefing O&G : cartographie 20 acteurs TSGP", "17h00 RDV Attijariwafa Dakar", "20h00 Dîner privé : 6 profils Sénégal P0"] },
      { phase: "J1", title: "Expo — Régulateurs & Opérateurs", items: ["09h00 Ouverture CICAD — identification délégations", "10h30 Prise de contact PETROSEN stand officiel", "13h00 CEO Roundtable O&G — networking structuré", "15h00 TotalEnergies Sénégal : RDV 30 min", "18h30 Side event CG : 12 profils O&G, cocktail discret"] },
      { phase: "J2", title: "Services & Startups", items: ["09h00 Project Pitches : scoring 5 startups O&G", "11h00 AFC / AfDB desks — LP potentiels", "14h00 Réunion mi-parcours : 15 contacts scorés", "16h00 BP / Kosmos Energy : équipes sénégalaises"] },
      { phase: "J3", title: "Clôture + Préparation Forum M7", items: ["09h00 Derniers RDVs — clôture expo", "11h00 Validation 10 membres chapitre Dakar", "14h00 NEXTEN Summit (si couplé) — digital souverain", "17h00 Départ ou nuit Dakar"] },
    ],
    people: [
      { name: "Direction PETROSEN", org: "PETROSEN", role: "Régulateur gaz sénégalais — positionnement CG corridor", priority: "P0", action: "RDV formel 20 min lors expo via stand officiel" },
      { name: "Direction TotalEnergies Sénégal", org: "TotalEnergies", role: "Opérateur principal gaz — contact stratégique", priority: "P0", action: "RDV 30 min J1 après-midi" },
      { name: "BP Sénégal / Kosmos Energy", org: "BP / Kosmos", role: "Opérateurs GTA et Sangomar — cœur TSGP nord", priority: "P1", action: "Rencontre équipes J2" },
      { name: "Direction AFC Dakar", org: "Africa Finance Corp", role: "Co-financement infrastructure O&G — LP institutionnel", priority: "P1", action: "AfDB/AFC desks J2" },
      { name: "Technip Energies Afrique", org: "Technip", role: "Engineering O&G — réseau ingénieurs et chefs de projet", priority: "P1", action: "Via réseau français sur place" },
    ],
    companies: [
      { name: "PETROSEN", type: "Régulateur", relevance: "Régulateur du gaz sénégalais — positionnement corridor CG" },
      { name: "TotalEnergies Sénégal", type: "Opérateur", relevance: "Production gaz offshore — partenaire stratégique TSGP nord" },
      { name: "BP Sénégal / Kosmos Energy", type: "Opérateur", relevance: "Projets GTA et Sangomar — premiers producteurs tronçon nord" },
      { name: "AFC", type: "DFI", relevance: "Co-financement infrastructure — LP institutionnel potentiel" },
      { name: "Ecobank / CBAO Sénégal", type: "Banque", relevance: "Financement projets énergie sénégalais" },
    ],
    campus: [
      { name: "ESP Dakar (École Sup. Polytechnique)", profile: "Ingénieurs O&G sénégalais", action: "Contacter direction — intervention CG sur corridor énergie" },
      { name: "ISEP Thiès", profile: "Formation technique pétrolière", action: "Profils terrain — futurs Talents Émergents axe Énergie" },
      { name: "Université Cheikh Anta Diop", profile: "Économie, droit, sciences", action: "Réseau alumni cadres mid-level Sénégal" },
    ],
    networks: [
      { name: "ONHYM (Office Hydrocarbures Maroc)", type: "Institutionnel", action: "Pont ONHYM-PETROSEN — présence conjointe expo" },
      { name: "OCP Africa / OCP Sénégal", type: "Corporate marocain", action: "Facilitation accès via présence établie" },
      { name: "Attijariwafa Sénégal", type: "Banque", action: "Réseau Benjelloun-Touimi activé J-1" },
      { name: "AFD Direction Énergie Afrique Ouest", type: "DFI", action: "LP institutionnel potentiel — financement corridor" },
    ],
    communities: [
      { name: "TotalEnergies Sénégal direction", role: "Opérateur principal — contact stratégique" },
      { name: "Technip Energies Afrique", role: "Engineering O&G — réseau ingénieurs" },
      { name: "AFD Direction Énergie Afrique Ouest", role: "Financements infrastructure — LP potentiel" },
    ],
    objectives: [
      { title: "Cartographier 15-20 acteurs privés TSGP nord", kpi: "20 acteurs cartographiés", status: "pending" },
      { title: "RDV PETROSEN confirmé", kpi: "1 RDV PETROSEN", status: "pending" },
      { title: "Préparer Forum des Capitales Dakar (M7)", kpi: "10 membres Dakar pré-confirmés", status: "pending" },
    ],
    opportunities: [
      { axis: "Énergie", title: "Services intelligence corridor TSGP 2027-2031", desc: "Premier gaz 2031 — positionnement anticipatoire 5 ans d'avance" },
      { axis: "Aut. Énergétique", title: "Carbon credits Sénégal", desc: "Cadre réglementaire en construction — first-mover advantage" },
      { axis: "Expansion", title: "NEXTEN Summit couplage numérique", desc: "Double scoring énergie + numérique en un déplacement" },
    ],
    logistics: [
      { item: "Vol Casa–Dakar", cost: "250–400€", timing: "J-30", notes: "Royal Air Maroc direct 2h30" },
      { item: "Hôtel (4 nuits)", cost: "600–1000€", timing: "J-30", notes: "King Fahd Palace ou Terrou-Bi" },
      { item: "Badge expo CICAD", cost: "200–500€", timing: "J-21", notes: "Catégorie Investor/VIP" },
      { item: "Side event cocktail (12 pers.)", cost: "500–800€", timing: "J-14", notes: "Salon privé hôtel" },
    ],
    followup: [
      { timing: "J+0", action: "Envoi mémorandum aux 20 contacts O&G", tool: "Email + PDF", kpi: "20 emails" },
      { timing: "J+1", action: "Confirmation RDV PETROSEN bilatéral post-expo", tool: "Email formel", kpi: "1 confirmation" },
      { timing: "J+7", action: "Rapport terrain : scoring + plan chapitre Dakar", tool: "Document", kpi: "1 rapport" },
      { timing: "J+14", action: "Validation liste intervenants Forum Capitales M7", tool: "Email", kpi: "10 noms confirmés" },
    ],
    programme12: {
      cityRole: "Ville Phase II — Validation Terrain Énergie & TSGP Nord",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Sourcing candidats Énergie", status: "secondary", partners: [
          { name: "ESP Dakar (École Sup. Polytechnique)", type: "Campus", action: "Identifier 3-5 ingénieurs O&G candidats cohorte — profils techniques corridor TSGP nord", deliverable: "5 candidatures énergie" },
          { name: "CRES (Centre de Recherches Économiques)", type: "Think tank", action: "Partenaire intelligence : notes blanches niveau 1 sur écosystème énergie sénégalais", deliverable: "1 accord CRES" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Ville hôte — immersion énergie", status: "primary", partners: [
          { name: "CTIC Dakar / Jokkolabs", type: "Incubateur/Coworking", action: "Signer accord hébergement cohorte Phase II : 4 semaines, espace + wifi + logistique", deliverable: "1 accord espace signé" },
          { name: "PETROSEN", type: "Régulateur", action: "Lettre d'introduction pour entretiens clients des équipes énergie — accès 20+ contacts O&G structurés", deliverable: "1 lettre PETROSEN" },
          { name: "TotalEnergies Sénégal / BP / Kosmos", type: "Corporates O&G", action: "Pipeline de 30+ entretiens clients pour équipes cohorte axe Autonomie Énergétique", deliverable: "30 entretiens pré-organisés" },
          { name: "Cabinet droit hydrocarbures Dakar", type: "Expert juridique", action: "Identifier 2 experts droit O&G + OHADA pour analyse réglementaire multi-pays Phase II", deliverable: "2 experts engagés" },
          { name: "Attijariwafa Sénégal", type: "Banque", action: "Accès réseau PME sénégalaises corridor pour tests de pricing équipes fintech/logistique", deliverable: "20 contacts PME" },
        ]},
        { phase: "Phase III — Création & Lancement", role: "Partenaires syndication Énergie", status: "secondary", partners: [
          { name: "AFC Dakar desk", type: "DFI", action: "Pré-briefer AFC comme co-investisseur Demo Day pour startups énergie corridor", deliverable: "1 AFC briefé" },
          { name: "AFD Direction Énergie", type: "DFI", action: "Explorer co-financement post-Demo Day pour startups énergie + carbon credits", deliverable: "1 exploration AFD" },
        ]},
      ],
    },
  },
  abidjan: {
    roadmap: [
      { phase: "J-30", title: "Préparation ADW", items: ["Contact CGECI direction — préparation pont CGEM-CGECI", "Email Attijariwafa CI — réseau Benjelloun-Touimi", "Cartographie DSIs grands groupes CI présents ADW"] },
      { phase: "J-1", title: "Arrivée + Institutionnels", items: ["12h00 Arrivée — Sofitel Ivoire check-in", "15h00 Visite Attijariwafa CI", "17h30 RDV CGECI direction", "20h00 Dîner privé : 6 profils C-level ivoiriens"] },
      { phase: "J1", title: "ADW — Corporate & Telecom", items: ["09h00 Ouverture ADW'26 — scan participants", "10h30 Panel DSI grands groupes : 5 contacts", "13h00 Déjeuner Club DSI Côte d'Ivoire", "15h00 Bilatérales : Orange CI, MTN CI", "18h30 Cocktail clôture J1 — scoring"] },
      { phase: "J2", title: "Startups & Ministère", items: ["09h00 Pitch startups ivoiriennes — 3 profils pipeline", "11h00 RDV Ministère Transition Numérique CI", "13h00 Déjeuner Chambre franco-ivoirienne", "15h30 Finalisation 20 profils scorés"] },
      { phase: "J3-4", title: "Terrain & Suivi", items: ["Visites : Africa Startup Hub, YUX Design, INPHB", "RDVs bilatéraux top 5 contacts", "Dîner : 8 profils membres chapitre Abidjan", "J4 matin : bilan scoring + plan suivi 30 jours"] },
    ],
    people: [
      { name: "Direction CGECI", org: "CGECI (patronat CI)", role: "Pont CGEM-CGECI — légitimité chapitre Abidjan", priority: "P0", action: "RDV formel J-1 via CGEM Maroc" },
      { name: "DSI Orange CI / MTN CI", org: "Orange / MTN", role: "Décideurs achat infrastructure numérique CI", priority: "P0", action: "Bilatérales planifiées J1" },
      { name: "Ministère Transition Numérique CI", org: "Gouvernement CI", role: "Briefing CG 20 min — positionnement institutionnel", priority: "P1", action: "RDV J2 via CGECI ou Ambassade" },
      { name: "Direction Chambre franco-ivoirienne", org: "CCIF", role: "200+ entreprises françaises — directeurs régionaux", priority: "P1", action: "Déjeuner J2" },
      { name: "Fondateurs Africa Startup Hub", org: "Incubateur CI", role: "Réseau fondateurs ivoiriens deeptech", priority: "P1", action: "Visite terrain J3" },
    ],
    companies: [
      { name: "CGECI", type: "Patronat", relevance: "Via CGEM — pont institutionnel naturel, levier légitimité" },
      { name: "Orange CI / MTN CI", type: "Telecom", relevance: "Profils C-level infrastructure — futurs clients startups CG" },
      { name: "Société Générale CI / Ecobank CI", type: "Banque", relevance: "Desks corporate Abidjan — financement corridor" },
      { name: "Bolloré Africa Logistics", type: "Logistique", relevance: "Dorsale physique Abidjan-Lagos — couche intelligence" },
      { name: "YUX Design", type: "Agence UX", relevance: "Pan-africaine — profils Talents Émergents CI" },
    ],
    campus: [
      { name: "INPHB (Institut National Polytechnique)", profile: "Ingénieurs CI — meilleure école technique", action: "Visite terrain J3 — proposer intervention CG" },
      { name: "HECI Abidjan", profile: "Management et entrepreneuriat", action: "Réseau alumni pour chapitre Abidjan" },
      { name: "Université Félix Houphouët-Boigny", profile: "Économistes et juristes", action: "Réseau académique corridor UEMOA" },
    ],
    networks: [
      { name: "Attijariwafa Côte d'Ivoire", type: "Banque marocaine", action: "Première banque marocaine Abidjan — réseau patron" },
      { name: "Cosumar / OCP CI", type: "Corporate marocain", action: "Présence industrielle marocaine — entrée corporate" },
      { name: "Chambre Franco-Ivoirienne", type: "Réseau entreprises", action: "200+ entreprises françaises — profils DG" },
      { name: "AFD Abidjan bureau", type: "DFI", action: "Direction régionale UEMOA — financements numériques" },
    ],
    communities: [
      { name: "BCP / CDG CI", role: "Banques marocaines présentes — réseau financier" },
      { name: "Business France Côte d'Ivoire", role: "Réseau export France-CI — contacts filiales tech" },
      { name: "Club DSI Côte d'Ivoire", role: "Décideurs IT grands groupes — profils acheteurs" },
    ],
    objectives: [
      { title: "20 contacts DSI / C-level ivoiriens", kpi: "20 fiches DSI/C-level", status: "pending" },
      { title: "Contact CGECI officiel pont CGEM-CGECI", kpi: "1 contact formalisé", status: "pending" },
      { title: "3 startups ivoiriennes pipeline CG", kpi: "3 startups CI pipeline", status: "pending" },
    ],
    opportunities: [
      { axis: "Expansion", title: "Chapitre Abidjan CG — fondation M12", desc: "ADW = recrutement 15-20 premiers membres hub UEMOA" },
      { axis: "Aut. Numérique", title: "Cloud UEMOA souverain", desc: "CI marché le plus mature UEMOA — moat réglementaire" },
      { axis: "Infrastructure", title: "Corridor Abidjan-Lagos physique", desc: "Couche intelligence sur dorsale Bolloré/CMA CGM" },
    ],
    logistics: [
      { item: "Vol Casa–Abidjan", cost: "350–550€", timing: "J-30", notes: "Royal Air Maroc direct 4h" },
      { item: "Hôtel Sofitel Ivoire (4 nuits)", cost: "800–1200€", timing: "J-30", notes: "Lieu de l'événement ADW" },
      { item: "Badge ADW", cost: "100–300€", timing: "J-21", notes: "VIP/Business" },
      { item: "Dîner privé (6-8 pers.)", cost: "300–500€", timing: "J-14", notes: "Restaurant Abidjan Cocody" },
      { item: "Vaccin fièvre jaune", cost: "50€", timing: "J-45 minimum", notes: "OBLIGATOIRE — délai 10 jours" },
    ],
    followup: [
      { timing: "J+0", action: "Scoring 20 contacts — classement P0-P3", tool: "Excel", kpi: "20 contacts" },
      { timing: "J+3", action: "Emails suivi CGECI + DSI contactés", tool: "Email + mémo", kpi: "10 emails" },
      { timing: "J+7", action: "Envoi propositions aux 3 startups CI pipeline", tool: "Email + deck", kpi: "3 propositions" },
      { timing: "J+30", action: "Rapport ADW + plan chapitre Abidjan", tool: "Document", kpi: "1 rapport" },
    ],
    programme12: {
      cityRole: "Ville Phase II — Validation Terrain Numérique UEMOA",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Sourcing candidats Numérique", status: "secondary", partners: [
          { name: "INPHB (Institut National Polytechnique)", type: "Campus", action: "Identifier 3-5 ingénieurs CI candidats cohorte — profils cloud/IA souverain", deliverable: "5 candidatures tech CI" },
          { name: "Africa Startup Hub Abidjan", type: "Incubateur", action: "Co-sourcing candidats avec incubateur local — profils fondateurs CI", deliverable: "3 profils co-sourcés" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Ville hôte — immersion numérique UEMOA", status: "primary", partners: [
          { name: "Africa Startup Hub / Jokkolabs Abidjan", type: "Coworking", action: "Accord hébergement cohorte Phase II : 4 semaines, espace + réseau local", deliverable: "1 accord espace" },
          { name: "CGECI (patronat CI)", type: "Institutionnel", action: "Pipeline 50+ entretiens clients via réseau CGECI — DSI grands groupes CI", deliverable: "50 entretiens pré-organisés" },
          { name: "Club DSI Côte d'Ivoire", type: "Réseau corporate", action: "Accès direct aux décideurs IT corporates CI pour tests de pricing cloud/SaaS", deliverable: "15 RDV DSI confirmés" },
          { name: "Orange CI / MTN CI", type: "Telecom", action: "POC partnerships : proposer aux équipes cohorte de tester avec infra telecom CI", deliverable: "2 POC explorés" },
          { name: "Cabinet OHADA Abidjan", type: "Expert juridique", action: "Expert droit OHADA + fiscalité UEMOA pour analyse réglementaire Phase II", deliverable: "1 expert engagé" },
        ]},
        { phase: "Phase III — Création & Lancement", role: "Partenaires syndication", status: "secondary", partners: [
          { name: "Attijariwafa CI / Ecobank CI", type: "Banque", action: "Pré-briefer comme co-investisseurs ou clients anchor post-Demo Day", deliverable: "2 banques briefées" },
          { name: "Chambre Franco-Ivoirienne", type: "Réseau", action: "200+ entreprises françaises CI — audience Demo Day francophone", deliverable: "10 entreprises invitées Demo Day" },
        ]},
      ],
    },
  },
  lagos: {
    roadmap: [
      { phase: "NOG J-30", title: "Préparation Nigeria", items: ["Visa Nigeria multi-entrée (couvre juil, août, oct)", "Réunion Ambassade Maroc Abuja — protocole", "Briefing NNPC via canaux ONHYM", "Réserver Transcorp Hilton Abuja + Eko Hotel Lagos"] },
      { phase: "NOG J1-5", title: "NOG Energy Week — Abuja (5-9 juil)", items: ["J1 Ouverture — sessions pipeline Nigeria-Maroc", "J2 Contact NNPC via Ambassade Maroc", "J3 B2B : 8 RDVs + sessions AFC/World Bank", "J4 Juniors indépendantes + Tony Attah", "J5 Scoring 30 contacts + vol Abuja→Lagos"] },
      { phase: "SPE J1-3", title: "SPE NAICE — Lagos (3-5 août)", items: ["J1 Sessions upstream + exhibition juniors", "J2 Young Professionals SPE (15 profils 28-38 ans)", "J2 soir Cocktail CG Eko Hotel — 30 profils", "J3 Scoring total + RDVs chapitre Lagos"] },
      { phase: "MOON J1-2", title: "Moonshot TechCabal — Lagos (28-29 oct)", items: ["J1 Identification Bosun Tijani (Ministre Digital)", "J1 Startup Village : scoring 20 startups cohorte 2", "J1 soir Side event CG : 30 Talents Émergents", "J2 Iyin Aboyeji (Future Africa) — co-investissement", "J2 TechCabal — pitch partenariat média corridor"] },
      { phase: "Bilan", title: "Consolidation Lagos M4-M10", items: ["Bilan total 3 événements Nigeria", "Scoring membres chapitre Lagos — projection M12", "Rapport Nigeria complet + plan 2027"] },
    ],
    people: [
      { name: "Bayo Bashir Ojulari", org: "NNPC", role: "CEO NNPC — interlocuteur corridor CG côté Nigeria", priority: "P0", action: "RDV 20 min NOG via Ambassade Maroc" },
      { name: "Tony Attah", org: "Renaissance Africa Energy", role: "Acteur nigérian indépendant clé O&G", priority: "P0", action: "RDV J3 NOG si obtenu" },
      { name: "Tomi Davies", org: "TVC Labs", role: "Connecteur central tech Nigeria (suite ATS London)", priority: "P0", action: "Activation réseau Lagos post-ATS" },
      { name: "Bosun Tijani", org: "Ministre Digital Economy NG", role: "Validateur politique souveraineté numérique Nigeria", priority: "P1", action: "Brief CG via intermédiaire Moonshot" },
      { name: "Iyin Aboyeji", org: "Future Africa", role: "Fonds early-stage Nigeria — co-investissement CG", priority: "P1", action: "RDV J2 Moonshot" },
      { name: "Fondateurs juniors NG (5 profils)", org: "Seplat, Heirs Energy, etc.", role: "Profils Bâtisseurs chapitre Lagos", priority: "P0", action: "Identification SPE NAICE" },
    ],
    companies: [
      { name: "NNPC", type: "National Oil Corp", relevance: "CEO Ojulari — positionnement CG corridor TSGP sud" },
      { name: "AFC (Africa Finance Corporation)", type: "DFI", relevance: "Co-investissement infrastructure — LP institutionnel P0" },
      { name: "NEXIM Bank Nigeria", type: "Banque export", relevance: "Financement export Nigeria-Maroc" },
      { name: "Renaissance Africa Energy", type: "Junior O&G", relevance: "Acteur indépendant clé — profil Bâtisseur" },
      { name: "Future Africa", type: "Fonds early-stage", relevance: "Co-investissement CG cohorte — Iyin Aboyeji" },
      { name: "TechCabal / Big Cabal Media", type: "Média tech", relevance: "Partenariat média corridor — couverture organique" },
    ],
    campus: [
      { name: "University of Lagos (UNILAG)", profile: "Petroleum Engineering — alumni actifs industry", action: "Réseau ingénieurs O&G pour Talents Émergents" },
      { name: "Pan-Atlantic University (LBS)", profile: "Lagos Business School — leaders secteur", action: "Event conjoint CG x LBS — investissement corridor" },
      { name: "Covenant University", profile: "Tech et business Nigeria — fondateurs", action: "Réseau alumni entrepreneurs" },
      { name: "FUTA (Fed. Uni. Technology Akure)", profile: "Ingénieurs terrain Nigeria", action: "Profils techniques O&G deeptech" },
    ],
    networks: [
      { name: "ONHYM délégation Nigeria", type: "Institutionnel marocain", action: "Présence officielle NOG — entrée naturelle" },
      { name: "OCP Nigeria desk", type: "Corporate marocain", action: "Infrastructure relationnelle établie Abuja" },
      { name: "TotalEnergies Nigeria", type: "Major française", action: "Réseau introductions C-level NG" },
      { name: "CCIFN (Chambre franco-nigériane)", type: "Réseau entreprises", action: "200+ entreprises françaises Nigeria" },
      { name: "Kairos Angels", type: "Angels network", action: "Co-investissement angel via Tayo Oviosu" },
      { name: "HoaQ Club", type: "Angel syndicate", action: "25+ startups financées — co-deals corridor" },
    ],
    communities: [
      { name: "Ambassade Maroc à Abuja", role: "Facilitation protocole et introductions ministérielles" },
      { name: "Technip FMC Nigeria", role: "Engineering O&G français — profils techniques senior" },
      { name: "Partech Africa Lagos team", role: "Fonds VC franco-nigérian — pipeline co-deals CG" },
    ],
    objectives: [
      { title: "Réunion NNPC / CEO Ojulari", kpi: "1 RDV NNPC obtenu", status: "pending" },
      { title: "3 juniors nigérianes identifiées", kpi: "3 profils Bâtisseurs NG O&G", status: "pending" },
      { title: "Positionnement CG discussions pipeline NG-MA", kpi: "1 prise de parole CG", status: "pending" },
      { title: "20 fondateurs juniors identifiés (SPE)", kpi: "5 profils Bâtisseurs", status: "pending" },
      { title: "30 Talents Émergents Lagos scorés (Moonshot)", kpi: "10 admissions TE chapitre", status: "pending" },
      { title: "RDV Bosun Tijani", kpi: "1 RDV Ministère Digital NG", status: "pending" },
    ],
    opportunities: [
      { axis: "Énergie", title: "Services intelligence TSGP côté Nigeria", desc: "Marché 500M€ horizon 2031 — positionnement avant construction" },
      { axis: "Capital", title: "AFC / NEXIM comme LP institutionnels", desc: "Mandats explicites corridor Nigeria-Maroc" },
      { axis: "Géopolitique", title: "NNPC au Sommet Dakhla (M9)", desc: "Preuve que CG représente les deux extrémités du corridor" },
      { axis: "Médias", title: "TechCabal partenaire média corridor", desc: "Couverture organique permanente — média de référence tech NG" },
    ],
    logistics: [
      { item: "Visa Nigeria multi-entrée", cost: "150–250€", timing: "J-60", notes: "OBLIGATOIRE — couvre juil+août+oct" },
      { item: "Vol Casa–Abuja (NOG)", cost: "400–700€", timing: "J-30", notes: "Via Lagos ou direct" },
      { item: "Transcorp Hilton Abuja (5 nuits NOG)", cost: "1000–1500€", timing: "J-30", notes: "QG délégation NOG" },
      { item: "Vol Abuja–Lagos", cost: "100–150€", timing: "J-14", notes: "45 min" },
      { item: "Eko Hotel Lagos (SPE 3 nuits + Moonshot 2 nuits)", cost: "800–1200€", timing: "J-30", notes: "Victoria Island" },
      { item: "Cocktail CG Lagos (30 pers.)", cost: "800–1200€", timing: "J-14", notes: "Salon privé Eko Hotel" },
      { item: "Vaccin fièvre jaune", cost: "50€", timing: "J-45", notes: "OBLIGATOIRE" },
    ],
    followup: [
      { timing: "J+0 (chaque event)", action: "Scoring contacts — P0-P3", tool: "Excel", kpi: "30+ par event" },
      { timing: "J+1 NOG", action: "Mémorandum CG aux contacts NNPC/AFC", tool: "Email formel", kpi: "5 emails" },
      { timing: "J+7 SPE", action: "Relance 5 profils Bâtisseurs juniors", tool: "Email/WhatsApp", kpi: "5 relances" },
      { timing: "J+7 Moonshot", action: "Invitations Talents Émergents retenus", tool: "Email + formulaire", kpi: "10 invitations" },
      { timing: "J+30 final", action: "Rapport Nigeria consolidé M4-M10", tool: "Document", kpi: "1 rapport" },
    ],
    programme12: {
      cityRole: "Ville Phase II principale — Validation Terrain Nigeria & TSGP Sud",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Sourcing candidats Nigeria", status: "secondary", partners: [
          { name: "Pan-Atlantic University (LBS)", type: "Campus", action: "Partenariat recrutement : MBA nigérians pour cohorte CG — profils business corridor", deliverable: "5 candidatures LBS" },
          { name: "TVC Labs (Tomi Davies)", type: "Réseau angels", action: "Co-sourcing candidats via réseau TVC — fondateurs tech Lagos pré-qualifiés", deliverable: "3 profils co-sourcés" },
          { name: "UNILAG Petroleum Engineering", type: "Campus", action: "Ingénieurs O&G nigérians — co-fondateurs techniques axe Énergie", deliverable: "3 profils techniques" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Ville hôte principale — immersion Nigeria", status: "primary", partners: [
          { name: "CcHUB Lagos / Zone Tech Park", type: "Incubateur/Coworking", action: "Accord hébergement cohorte Phase II : 4 semaines, espace + réseau + mentors locaux", deliverable: "1 accord espace signé" },
          { name: "NNPC / juniors indépendantes (Seplat, Heirs Energy)", type: "Corporate O&G", action: "Pipeline 100+ entretiens clients structurés pour équipes énergie — accès via NOG contacts", deliverable: "100 entretiens planifiés" },
          { name: "Future Africa (Iyin Aboyeji)", type: "Fonds early-stage", action: "Mentorat intensif équipes cohorte + accès réseau fondateurs portfolio Future Africa", deliverable: "1 accord mentorat" },
          { name: "Kairos Angels / HoaQ Club", type: "Angel syndicates", action: "Accès deal flow partagé + mentors angels pour coaching Phase II", deliverable: "5 mentors angels confirmés" },
          { name: "CCIFN (Chambre franco-nigériane)", type: "Réseau", action: "Pipeline entretiens clients corporates français implantés Nigeria — 30 contacts", deliverable: "30 entretiens" },
          { name: "Cabinet droit nigérian (Lagos)", type: "Expert juridique", action: "Expert droit sociétés Nigeria + réglementation NUPRC pour analyse multi-pays", deliverable: "2 experts engagés" },
        ]},
        { phase: "Phase III — Création & Lancement", role: "Co-investisseurs + Demo Day", status: "primary", partners: [
          { name: "AFC (Africa Finance Corporation)", type: "DFI", action: "LP institutionnel Demo Day — co-investissement infrastructure post-programme", deliverable: "1 AFC confirmé Demo Day" },
          { name: "NEXIM Bank Nigeria", type: "Banque export", action: "Financement export Nigeria-Maroc pour startups corridor post-Demo Day", deliverable: "1 NEXIM briefé" },
          { name: "Future Africa + Kairos Angels", type: "Fonds + Angels", action: "Syndicate co-investissement Demo Day — 5-8 investisseurs nigérians pré-engagés", deliverable: "5 investisseurs NG pré-engagés" },
          { name: "TechCabal", type: "Média", action: "Couverture Demo Day — visibilité organique écosystème tech Nigeria", deliverable: "1 accord média" },
        ]},
      ],
    },
  },
  accra: {
    roadmap: [
      { phase: "J-30", title: "Préparation DASA + AMDS", items: ["Cartographie 30 cibles DASA + 20 cibles AMDS", "Contact Bank Al-Maghrib — représentation CBDC", "Réserver Kempinski Hotel Gold Coast"] },
      { phase: "J-1", title: "Arrivée Accra", items: ["13h00 Check-in Kempinski", "17h00 Réunion préparatoire : listes cibles", "20h00 Dîner privé : 8 fondateurs fintech Ghana"] },
      { phase: "J1-2", title: "DASA — Banques Centrales & Régulateurs", items: ["09h00 Ouverture — Bank of Ghana keynote", "10h30 Central Banks Forum : BoG, CBN, BCEAO", "14h00 Regulatory Roundtable : pitch CG deal flow sandbox", "16h00 Bilatéraux : 4 banques centrales + 3 fonds dev", "19h30 Side event CG Accra : 20 profils, Kempinski"] },
      { phase: "J3-4", title: "AMDS — Fondateurs Web3 & Clôture", items: ["J3 Africa Money & DeFi Summit — scan fondateurs", "J3 Panel paiements transfrontaliers : 5 fondateurs", "J3 Zeepay, Chipper Cash alumni : rencontres", "J4 Bilan : 50 contacts scorés, top 10 relancés", "J4 Départ Accra — mémorandum envoyé sur le vol"] },
    ],
    people: [
      { name: "Direction Bank of Ghana", org: "Bank of Ghana", role: "Régulateur hôte — crédibilité institutionnelle maximale", priority: "P0", action: "Contact post-keynote J1" },
      { name: "Direction SEC Ghana", org: "SEC Ghana", role: "Régulation crypto et actifs numériques corridor", priority: "P1", action: "Regulatory Roundtable J1" },
      { name: "BCEAO / CBN Nigeria présents", org: "Banques centrales", role: "LP institutionnels — CBDC transfrontalier", priority: "P0", action: "Central Banks Forum J1" },
      { name: "Direction Zeepay Ghana", org: "Zeepay", role: "Fintech paiements transfrontaliers corridor", priority: "P1", action: "Rencontre structurée J3 AMDS" },
      { name: "GSMA Mobile Money Africa", org: "GSMA", role: "Infrastructure paiements corridor", priority: "P1", action: "Panel AMDS" },
    ],
    companies: [
      { name: "Bank of Ghana", type: "Banque centrale", relevance: "Hôte DASA — crédibilité institutionnelle corridor" },
      { name: "Ecobank Group (siège Lomé / desk Accra)", type: "Banque panafricaine", relevance: "Réseau 33 pays — financement corridor" },
      { name: "Zeepay Ghana", type: "Fintech", relevance: "Paiements transfrontaliers — thèse directe CG" },
      { name: "African Development Bank fintech", type: "DFI", relevance: "Programme fintech — LP institutionnel" },
      { name: "Fidelity Bank Ghana / Cal Bank", type: "Banque locale", relevance: "Profils banquiers locaux Ghana" },
    ],
    campus: [
      { name: "Université du Ghana (Legon)", profile: "Alumni économie et finance", action: "Réseau académique chapitre Accra" },
      { name: "GIMPA", profile: "Cadres publics — Ghana Institute Management", action: "Profils gouvernance et régulation" },
      { name: "Ashesi University", profile: "Tech et entrepreneuriat anglophone — élite", action: "Profils Talents Émergents anglophones" },
    ],
    networks: [
      { name: "Bank Al-Maghrib (dirham digital)", type: "Banque centrale MA", action: "Pont naturel avec DASA — représentation CBDC" },
      { name: "CIH Bank / CDG digital", type: "Finance digitale MA", action: "Profils connexion Ghana" },
      { name: "AFD Accra / West Africa desk", type: "DFI", action: "Financement digital public — LP potentiel" },
      { name: "Société Générale Ghana", type: "Banque française", action: "Réseau corporate local" },
    ],
    communities: [
      { name: "French Tech Africa (BPI)", role: "Fondateurs franco-ghanéens tech présents" },
      { name: "ECOWAS Secretariat Accra", role: "Région CEDEAO — positionnement panafricain" },
      { name: "CGEM Tech Maroc", role: "Délégation tech marocaine si présente" },
    ],
    objectives: [
      { title: "3 banques centrales corridor briefées", kpi: "3 banques centrales contactées", status: "pending" },
      { title: "5 fondateurs fintech/Web3 pipeline cohorte 2", kpi: "5 fondateurs pipeline C2", status: "pending" },
      { title: "CG comme deal flow pour sandbox régulateurs", kpi: "2 MOU sandbox", status: "pending" },
      { title: "Chapitre Accra CG initié", kpi: "5 membres fondateurs identifiés", status: "pending" },
    ],
    opportunities: [
      { axis: "Aut. Numérique", title: "CBDC transfrontalière corridor", desc: "MAD-CFA-Naira — monopole à moat réglementaire ultime" },
      { axis: "Web3", title: "Tokenisation actifs réels corridor", desc: "Terres, droits miniers, carbon credits — gouvernance CG" },
      { axis: "Ghana", title: "Chapitre Accra — hub anglophone CEDEAO", desc: "Complète la géographie sur le flanc anglophone" },
    ],
    logistics: [
      { item: "Vol Casa–Accra", cost: "400–600€", timing: "J-30", notes: "Via Abidjan ou direct" },
      { item: "Kempinski Hotel (4 nuits)", cost: "800–1400€", timing: "J-30", notes: "Lieu événement DASA" },
      { item: "Badge DASA + AMDS", cost: "300–600€", timing: "J-21", notes: "Back-to-back = 1 déplacement" },
      { item: "Side event CG (20 pers.)", cost: "600–1000€", timing: "J-14", notes: "Salon Kempinski" },
    ],
    followup: [
      { timing: "J+0", action: "Scoring 50 contacts — top 10 immédiat", tool: "Excel", kpi: "50 contacts" },
      { timing: "J+1", action: "Mémorandum CG aux banques centrales", tool: "Email formel", kpi: "3 emails" },
      { timing: "J+7", action: "Propositions MOU sandbox aux 2 régulateurs", tool: "Email + draft MOU", kpi: "2 propositions" },
      { timing: "J+14", action: "Relance fondateurs fintech pipeline C2", tool: "WhatsApp/Email", kpi: "5 relances" },
      { timing: "J+30", action: "Rapport Accra + plan chapitre", tool: "Document", kpi: "1 rapport" },
    ],
    programme12: {
      cityRole: "Ville Phase II — Validation Terrain Fintech/Web3 & Régulation Anglophone",
      phases: [
        { phase: "Phase I — Cristallisation", role: "Sourcing candidats Web3/Fintech", status: "secondary", partners: [
          { name: "Ashesi University", type: "Campus", action: "Identifier 3-5 profils tech/entrepreneuriat anglophones — élite Ghana", deliverable: "5 candidatures Ashesi" },
          { name: "GIMPA (Ghana Institute Management)", type: "Campus", action: "Cadres publics ghanéens — profils gouvernance et régulation fintech", deliverable: "3 profils governance" },
        ]},
        { phase: "Phase II — Validation Terrain", role: "Ville hôte — immersion fintech/régulation", status: "primary", partners: [
          { name: "iSpace Ghana / Kumasi Hive", type: "Incubateur/Coworking", action: "Accord hébergement cohorte Phase II : 4 semaines, espace Accra", deliverable: "1 accord espace signé" },
          { name: "Bank of Ghana / SEC Ghana", type: "Régulateurs", action: "Accès sandbox réglementaire pour équipes fintech/Web3 — MOU formalisant l'accès", deliverable: "1 MOU sandbox signé" },
          { name: "Zeepay / Chipper Cash alumni", type: "Fintech", action: "Pipeline 50+ entretiens clients pour équipes paiements transfrontaliers corridor", deliverable: "50 entretiens planifiés" },
          { name: "BCEAO / CBN Nigeria (via DASA)", type: "Banques centrales", action: "Analyse réglementaire CBDC multi-pays pour équipes cohorte axe Autonomie Numérique", deliverable: "3 briefings banques centrales" },
          { name: "Ecobank Group (desk Accra)", type: "Banque panafricaine", action: "Entretiens clients corporate pour tests de pricing — réseau 33 pays", deliverable: "20 entretiens Ecobank" },
        ]},
        { phase: "Phase III — Création & Lancement", role: "Régulateurs + audience Demo Day", status: "secondary", partners: [
          { name: "AfDB fintech programme", type: "DFI", action: "LP institutionnel Demo Day — co-financement startups fintech corridor", deliverable: "1 AfDB briefé Demo Day" },
          { name: "GSMA Mobile Money Africa", type: "Infrastructure", action: "Partenariat post-Demo Day pour startups paiements mobile corridor", deliverable: "1 accord GSMA exploré" },
          { name: "Bank of Ghana sandbox", type: "Régulateur", action: "Accès sandbox post-Demo Day pour startups qualifiées — avantage compétitif unique", deliverable: "Sandbox access confirmé" },
        ]},
      ],
    },
  },
  chine: {
    roadmap: [],
    people: [],
    companies: [],
    campus: [],
    networks: [],
    communities: [],
    objectives: [],
    opportunities: [],
    logistics: [],
    followup: []
  }
};
